### PR TITLE
Remove deleted Pivotal stories

### PR DESCRIPTION
**Pull request by cleicar**
This will address issue: https://github.com/fastruby/dash/issues/34

### CODE REVIEW

**Review by arielj — CHANGES_REQUESTED** [review]
There's a problem with this after testing it locally. The background job only checks for projects that changed to speed it up (keeping track of the project version number), so the `_stories` array only includes the stories for the projects that changed and not all the stories of a user, making this method delete all the stories for projects that didn't change since those stories are not in the array.

**Comment by arielj** [comment]
We should also add tests for a feature that will delete stuff.

**Comment by etagwerker** [comment]
@cleicar Could you please post an update about this PR? Thanks!

**Comment by cleicar** [comment]
@arielj Nice catch! I didn't get that when I was doing these changes.

I agree with the test coverage, as this is still a WIP story, that sadly I didn't have time to finish before I leave to vacation :(

**Review by rdormer — APPROVED** [review]

**Review by bronzdoc — CHANGES_REQUESTED** [review]
Needs a spec and address comments

**Comment by bronzdoc** [comment]
@cleicar just checking if you plan to continue working on this or should we close it?

**Comment by cleicar** [comment]
@bronzdoc I plan to keep but I need help. Let's talk about this in Slack :)

**Comment by cleicar** [comment]
@bronzdoc this is ready to review!

Thanks for the help @arielj 😬

**Review by rdormer — APPROVED** [review]

**Review by bronzdoc — APPROVED** [review]
LGTM!

**Comment by bronzdoc** [comment]
@ABizzinotto this is ready for QA

**Comment by ABizzinotto** [comment]
@cleicar @bronzdoc this is ready to merge

**Pull request merged**
