### PR TITLE
Add task to update pivotal stories for all users

### LINKED ISSUE #3: Sync Pivotal Stories task.
As a user, I would like to see my pivotal stories with their updated status without having to enqueue a sync job.

**Why**
I want to see an updated list of pivotal stories every time I load the page
So that I don't have to synchronously sync my pivotal stories

**Scenario:** 
Given that pivotal stories are constantly being updated
When I sign back in and open my dashboard
Then I should see a list of pivotal stories with their up to date status

**Notes:**
There should be a regular cron job (Heroku scheduler) that runs a rake task which does this:

Find all open pivotal stories in our system database
Call the Pivotal Tracker API to find the pivotal stories updated status and list of assignees
Update our database accordingly

### PR DESCRIPTION
**Pull request by cleicar**
closes #3

Description:

Add a new task to update the pivotal tracker stories as same as we do for GitHub issues and pull requests

### CODE REVIEW

**Review by bronzdoc — APPROVED** [review]
LGTM

**Comment by bronzdoc** [comment]
@cleicar how can we QA this PR?

**Comment by etagwerker** [comment]
@cleicar @bronzdoc I deployed these changes to staging (they are still there) and I found an error: 

```
2021-08-23T00:04:42.709256+00:00 app[worker.1]: pid=4 tid=fh4 WARN: ActiveRecord::ActiveRecordError: cannot update a new record
2021-08-23T00:04:42.709440+00:00 app[worker.1]: pid=4 tid=fh4 WARN: /app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.3.2/lib/active_record/persistence.rb:665:in `update_columns'
2021-08-23T00:04:42.709441+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.3.2/lib/active_record/persistence.rb:645:in `update_column'
2021-08-23T00:04:42.709441+00:00 app[worker.1]: /app/app/models/pivotal_project.rb:18:in `update_version'
2021-08-23T00:04:42.709441+00:00 app[worker.1]: /app/app/models/pivotal_project.rb:6:in `sync_with'
2021-08-23T00:04:42.709442+00:00 app[worker.1]: /app/app/workers/pivotal_worker.rb:15:in `block in perform'
2021-08-23T00:04:42.709442+00:00 app[worker.1]: /app/app/workers/pivotal_worker.rb:13:in `map'
2021-08-23T00:04:42.709443+00:00 app[worker.1]: /app/app/workers/pivotal_worker.rb:13:in `perform'
2021-08-23T00:04:42.709443+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:196:in `execute_job'
2021-08-23T00:04:42.709444+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:164:in `block (2 levels) in process'
2021-08-23T00:04:42.709444+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/middleware/chain.rb:133:in `invoke'
2021-08-23T00:04:42.709445+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:163:in `block in process'
2021-08-23T00:04:42.709445+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
2021-08-23T00:04:42.709445+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/job_retry.rb:112:in `local'
2021-08-23T00:04:42.709446+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
2021-08-23T00:04:42.709446+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/rails.rb:14:in `block in call'
2021-08-23T00:04:42.709446+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/execution_wrapper.rb:88:in `wrap'
2021-08-23T00:04:42.709447+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/reloader.rb:72:in `block in wrap'
2021-08-23T00:04:42.709447+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/execution_wrapper.rb:88:in `wrap'
2021-08-23T00:04:42.709447+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/reloader.rb:71:in `wrap'
2021-08-23T00:04:42.709448+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/rails.rb:13:in `call'
2021-08-23T00:04:42.709448+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
2021-08-23T00:04:42.709448+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:257:in `stats'
2021-08-23T00:04:42.709448+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
2021-08-23T00:04:42.709449+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/job_logger.rb:13:in `call'
2021-08-23T00:04:42.709449+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
2021-08-23T00:04:42.709449+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/job_retry.rb:79:in `global'
2021-08-23T00:04:42.709449+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:124:in `block in dispatch'
2021-08-23T00:04:42.709450+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/logger.rb:11:in `with'
2021-08-23T00:04:42.709450+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/job_logger.rb:33:in `prepare'
2021-08-23T00:04:42.709450+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:123:in `dispatch'
2021-08-23T00:04:42.709451+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:162:in `process'
2021-08-23T00:04:42.709451+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:78:in `process_one'
2021-08-23T00:04:42.709451+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:68:in `run'
2021-08-23T00:04:42.709451+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/util.rb:43:in `watchdog'
2021-08-23T00:04:42.709452+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/util.rb:52:in `block in safe_thread'
2021-08-23T00:04:54.479816+00:00 app[api]: Starting process with command `bundle exec rake update_pull_requests` by user scheduler@addons.heroku.com
2021-08-23T00:04:59.567550+00:00 heroku[scheduler.8761]: Starting process with command `bundle exec rake update_pull_requests`
2021-08-23T00:05:00.220801+00:00 heroku[scheduler.8761]: State changed from starting to up
2021-08-23T00:05:04.699138+00:00 app[scheduler.8761]: Updating pull requests...
2021-08-23T00:05:12.431877+00:00 app[scheduler.8761]: done.
2021-08-23T00:05:12.490978+00:00 heroku[scheduler.8761]: Process exited with status 0
2021-08-23T00:05:12.664990+00:00 heroku[scheduler.8761]: State changed from up to complete
```

**Comment by cleicar** [comment]
@etagwerker I just tested and the deploy was successful, I tested all the tasks locally and they seems to be working. This might be an issue that only happened end with this deploy.

@bronzdoc I am not sure how to test it. Maybe you can delete all the PT stories for your user and see if they will show up after running the task. For that you can run the task manually via heroku console or (even better) use the scheduler plugin in the staging environment to see if it will update the stories. Let me know if I can assist in this.

**Comment by bronzdoc** [comment]
@cleicar can you check the error that @etagwerker reported, please? Thanks!

**Comment by cleicar** [comment]
@bronzdoc Did you see my comment above? I think that there's no issue at all :)

**Pull request merged**
